name: realtime_innovations_task
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

isar_version: &isar_version 3.1.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  go_router: ^14.7.2
  flutter_svg: ^2.0.17
  table_calendar: ^3.2.0
  intl: ^0.20.2
  path_provider:
  isar: *isar_version
  isar_flutter_libs: *isar_version
  dartz:
  get_it:




dev_dependencies:
  isar_generator: *isar_version
  build_runner: any
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/svgs/


